// Stub for common/build-info.cpp.in, which is normally generated by CMake
// at configure time from the build environment (git commit, compiler, etc).
// chat.cpp's COM_TRC() logging macro references llama_build_number(),
// llama_commit(), llama_compiler(), and llama_build_target(); these have no
// bearing on chat-template behavior, so fixed placeholder values are used.

#include "build-info.h"

#include <cstdio>
#include <string>

int LLAMA_BUILD_NUMBER = 0;
char const * LLAMA_COMMIT = "unknown";
char const * LLAMA_COMPILER = "unknown";
char const * LLAMA_BUILD_TARGET = "unknown";

int llama_build_number(void) {
    return LLAMA_BUILD_NUMBER;
}

const char * llama_commit(void) {
    return LLAMA_COMMIT;
}

const char * llama_compiler(void) {
    return LLAMA_COMPILER;
}

const char * llama_build_target(void) {
    return LLAMA_BUILD_TARGET;
}

const char * llama_build_info(void) {
    static std::string s = "b" + std::to_string(LLAMA_BUILD_NUMBER) + "-" + LLAMA_COMMIT;
    return s.c_str();
}

void llama_print_build_info(void) {
    fprintf(stderr, "%s: build = %d (%s)\n",      __func__, llama_build_number(), llama_commit());
    fprintf(stderr, "%s: built with %s for %s\n", __func__, llama_compiler(), llama_build_target());
}
